### ISSUE TITLE
Reboot Necessary in Batman Role

### ISSUE THREAD

**Issue by CodeFetch** [freifunkh/ansible#106]
Building Batman failed, because my system needed a reboot after it has updated to a new kernel version. Thus we should introduce a check for `/var/run/reboot-required`.

**Comment by 1977er** [comment]
This is already covered by checks and notifications in Zabbix (monitoring). Do you need further automation?

**Comment by CodeFetch** [comment]
I've tried to deploy the supernode role on a new machine which failed and the machine needed a reboot to be accessible again... The check is missing at deployment time.

**Comment by 1977er** [comment]
Do you know the exact reason why it stucked? Randomly rebooting machines is quite a big hammer.

**Comment by CodeFetch** [comment]
I think it tried to use the wrong linux-headers as the kernel was previously upgraded, but not loaded, yet. Maybe it's enough to always test for the flag before touching anything... The problem was that the firewall was already erected at that point.

**Comment by CodeFetch** [comment]
You understood me wrong. I was happy that I could access the machine again after a reboot. My suggestion is not to do a reboot, but to prohibit deploying the roles if a restart is needed.

**Comment by 1977er** [comment]
OIC, so you request a conditional on "/var/run/reboot-required exists"? If yes, please go ahead.

**Comment by AiyionPrime** [comment]
The problem with the firewall does still stand right?
Is rebooting safe at that place? Or does on get locked out @codefetch?

**Comment by CodeFetch** [comment]
@AiyionPrime Yes if there was a reboot needed and e.g. Batman is not running properly, bad things can happen like getting locked out because of a missing firewall rule. When you update a system, the running processes will not change, unless you e.g. restart them, what some ansible roles do. So when a reboot is required, e.g. when loading a new version of a kernel module is required, but the old one can't be unloaded, it needs to be rebooted first. Actually it would make sense to install / update all dependencies / utilities before rolling new changes of ours. Therefore we either need to use "fix" versions / commits of programs instead of using the master or something and when we update such a thing, we need to roll it out on all nodes, so that our other ansible roles configuration changes don't interfere. So I tend to close this and open a new issue "Don't break ansiblespace"

**Comment by 1977er** [comment]
With respect to long term "needs reboot", there is a trigger in Zabbix which informs us about outstanding reboots.

**Comment by AiyionPrime** [comment]
> can't be unloaded, it needs to be rebooted first.

My question aimed for, whether a reboot right in front of the possible failing unload would be safe, or if we get locked out there as well.

**Comment by CodeFetch** [comment]
@AiyionPrime The problem was that someone or something required a reboot. So rebooting before touching anything and rebooting after rolling changes if a reboot is needed would be nice.

**Comment by lemoer** [comment]
I added the milestone "Beginn der stabilen Phase", as this is marked as bug and should therefore fixed before the "stabile Phase".

**Comment by AiyionPrime** [comment]
> @AiyionPrime The problem was that someone or something required a reboot. So rebooting before touching anything and rebooting after rolling changes if a reboot is needed would be nice.

Yeah, I agree, but that's still no answer to my question, I'm afraid?

**Comment by CodeFetch** [comment]
@AiyionPrime I don't think it is a good idea to do a reboot while rolling. So my answer is: I don't know, but I wouldn't want to try it.

**Comment by 1977er** [comment]
I'm writing a pre-task, which shows a warning banner in case a reboot is necessary.

**Comment by lemoer** [comment]
@1977er will fix this in about half an hour. Then the milestone is achieved and we can start with the infrastructure freeze week.

**Comment by 1977er** [comment]
Closing.
