### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by CodeFetch** [freifunkh/ansible#108]

**Comment by AiyionPrime** [comment]
tldrlegal.com/license/idgaf-v1.0

womöglich mit der Bitte, dass wenn unsere Repo geholfen hat ein Problem zu lösen über eine Firmen-Spende an FNorden nachgedacht werden könnte.

**Comment by 1977er** [comment]
Lizenz wofür?

**Comment by AiyionPrime** [comment]
@CodeFetch ausformulierte Frage lautete: "Unter welcher Lizenz steht eigentlich unsere ansible-repo" mit dem Ziel, anderen Menschen mehr rechtliche Sicherheit und weniger schlechtes Gewissen beim abschreiben und Inspirationen sammeln von unseren Rollen zu geben.

Man hat ihn Donnerstag getreten das in einem issue zu klären, das tut er jetzt.
Wenn du Vorschläge hast, unter welcher Lizenz wir veröffentlichen könnten, immer her damit.

**Comment by 1977er** [comment]
Schon klar. ;-) Ich fand nur die einzeilige Überschrift ohne weitere Beschreibung ein wenig dünn. ;-)

Ich finde die IDGAF angemessen.

**Comment by AiyionPrime** [comment]
@lemoer @Suuush ?

**Comment by lemoer** [comment]
MIT.

**Comment by 1977er** [comment]
Vorschlag: Wir sammeln bis zum 04.02.2021 und entscheiden dann beim Mumble-Treffen. Ich mache nochmal einen Rundruf auf intern@.

**Comment by tobby88** [comment]
> MIT.

MIT klingt gut, IDGAF wäre aber sicherlich auch ok.

**Comment by Manawyrm** [comment]
Ich bin ebenfalls für MIT und bestätige hiermit nochmal, dass alle meine Commits unter MIT lizenziert werden dürfen. 

IDGAF/WTFPL/etc. sind immer etwas unangenehm, wenn tatsächlich Code reused wird. Bei diesem Ansible-Repo glaub ich zwar nicht dran, dass das mal irgendwo mitgeliefert wird, aber es schadet nicht, MIT zu nehmen :)

**Comment by 1977er** [comment]
@eaxi schrieb per Mail:
> Macht wir ihr denkt. Ich bin immer von CC-BY-SA 4.0 ausgegangen.

**Comment by Suuush** [comment]
MIT ist ok für mich.

**Comment by 1977er** [comment]
Mit MIT können alle leben. Wir machen das jetzt mit MIT.

**Comment by 1977er** [comment]
LICENSE hinzugefügt.
