### ISSUE TITLE
Decide how and where to create bat interfaces

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#111]
Currently the only thing that prevents us from interface errors and race conditions regarding batman is a hotfix in #94 and #95.
Leo and I agreed on not caring for about half a year; until either systemd-networkd has batman support;
or batctl gets rid of the race condition.

Both progresses can be viewed [here](https://github.com/systemd/systemd/pull/17252) and [here](https://git.open-mesh.org/batctl.git/commit/5d465bfd9a19c4bda20fb4e36c6e4b22c56ceb17).

The latter is merged since [eight days](https://git.open-mesh.org/batctl.git/commit/a0da92b735f92fed42104614962b165acb751b2f) but is only available on the master branch until a new release appears.

In case waiting is still not an option, @1977er may examine how the task of creating bat interfaces may become asperated role from ffh.mesh_fastd and its competitors wireguard and tunneldigger.

**Comment by 1977er** [comment]
I wasn't aware of the larger picture.

**Comment by T-X** [comment]
The change to batctl should be available with the latest release now, v2021.0: https://www.open-mesh.org/news/100

**Comment by AiyionPrime** [comment]
Which is quite an amazing response time. I'll take care of the first tests after breakfast.
Therefore sn07 will be unstable for at least two hours.

**Comment by AiyionPrime** [comment]
sn07 uns on 2021.0 since then

**Comment by AiyionPrime** [comment]
batctl 2021.0 works flawlessly, sn07 tested it's features; seems to be stable.
The race condition is gone; so a viable answer is "create the bat interface everywhere using `meshif bat%I if add`".

I've done it for wireguard in #144, 

`systemctl list-units --type=service --all` shows the effect after a reboot.

**Comment by AiyionPrime** [comment]
the supernode and tunneldigger role do it the same way:

https://github.com/freifunkh/ansible/blob/4ce6ff3365872f8ca5cba54be541c2a9a5f9acb6/roles/ffh.supernode/templates/addtobatX.j2#L8

https://github.com/freifunkh/ansible/blob/4ce6ff3365872f8ca5cba54be541c2a9a5f9acb6/roles/ffh.mesh_tunneldigger/templates/addbrl2tptobatX%40.service.j2#L8

For now this appears to be settled. @1977er please close if you agree.
