### ISSUE TITLE
sn01: rsyslogd and telegraf

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#114]
On sn01 is a file in /etc/rsyslog.d/50-telegraf.conf, that's not part of this repo.
This file is currently producing a ton of warning messages.

Either this is some artifact of a removed role, or somebody handcrafted this gem.

Either way, if one of you could look into this and tell what that file is or was supposed to do, it would be nice.

the relevant parts of the file:
```
# discard DHCP requests!!
*.=info ~

# forward over tcp with octet framing according to RFC 5425
*.* @@(o)127.0.0.1:6514;RSYSLOG_SyslogProtocol23Format
```

**Comment by lemoer** [comment]
It is legacy stuff. Should be silenced via apt remove rsyslogd.

**Comment by 1977er** [comment]
Not sure if rsyslogd is used by anything else on the system. Older versions of our telegraf role must have created the config sniplet mentioned above.

I removed the rsyslog package, removed the sniplet and reinstalled the package again. Should be silent now. Closing.
