### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#118]
Things to Backup:
- [x] Wiki
- [x] Grafana (how?)
- [ ] Influx?
- [x] Zabbix

**Comment by 1977er** [comment]
Wir brauchen einen Ort, an dem wir kostengünstig ein paar TB abladen können.

- 32G für die web-VM inkl. Wiki. 
   - 600M für das Wiki alleine
- 32G + 256G für die harvester-VM inkl. Influx, Grafana und ggf noch Prometheus
   - 131G InfluxDB
   - 95G Prometheus (abgekündigt)
   - 35M Grafana (einfache SQLite DB)

**Comment by CodeFetch** [comment]
Der Hypervisor von sn08 hat Platz ;-)

**Comment by 1977er** [comment]
@CodeFetch:
Ist vermutlich besser, das in eine VM zu packen, um es potentiell von anderen Kundendaten wegzukapseln. Hast Du da noch Legacy IP-Adressen übrig oder wollen wir das mit v6-only machen?

**Comment by AiyionPrime** [comment]
@CodeFetch v6, oder v4, dass ist hier die Frage :)

**Comment by AiyionPrime** [comment]
Ich hätte gerne backups vom gitolite.
Was das ganze etwas schwieriger macht, weil die verschlüsselt sein sollten.

**Comment by lemoer** [comment]
Verschlüsselung ist geplant.

**Comment by AiyionPrime** [comment]
https://github.com/arillso/ansible.restic

**Comment by lemoer** [comment]
I pushed my backup role in #176. The backup host is not available yet, therefore I created only a PR and did not merge it onto master directly. @1977er wants to deploy the backup host tomorrow. Then he can use #176 to install some initial backups.

#176 covers:
- /etc/ on all hosts
- /var/www/ on web (backup of wiki)
- /home/git/ on ns1 (backup of gitolite)

Further stuff can be added later.

**Comment by lemoer** [comment]
@1977er Why did you close this?

**Comment by lemoer** [comment]
I just pushed (and rolled) a commit to backup grafana. With Plugins this takes ~110 MB of storage.

**Comment by lemoer** [comment]
Maybe we should discuss on Thursday what's left here? Or so?

**Comment by 1977er** [comment]
The only thing thats left open is whether we should/could backup influx.

**Comment by lemoer** [comment]
Zabbix should definitely also be backed up.

**Comment by lemoer** [comment]
Regarding zabbix: I looked into the size of the mysql tables:

```
+--------------------+----------------------------------------------------+-----------+
| Database           | Table                                              | Size (MB) |
+--------------------+----------------------------------------------------+-----------+
| zabbix             | history_uint                                       |     32686 |
| zabbix             | history                                            |      5075 |
| zabbix             | trends_uint                                        |      1423 |
| zabbix             | history_text                                       |       386 |
| zabbix             | trends                                             |       269 |
| zabbix             | history_str                                        |        20 |
| zabbix             | alerts                                             |         8 |
| zabbix             | items                                              |         5 |
| zabbix             | events                                             |         4 |
...
```

**Comment by lemoer** [comment]
CC: @1977er Can we just leave out the tables `history_uint`, `history`, `trends_uint`, `history_text`, `trends` for the backup?

**Comment by 1977er** [comment]
Spitting out a zabbix mysqldump without the forementioned big tables. Let restic backup the sql file. See zabbix-sql role.

**Comment by lemoer** [comment]
Can we consider it done?

**Comment by lemoer** [comment]
Yes. @1977er said in mumble, that it's done. So only influx is left now.

**Comment by 1977er** [comment]
Influx is quite big. We could

1. reduce the retention time from 6mo to 1w
2. skip the data at all
3. buy new hardware every now and then

I prefer 1) or 2).

**Comment by 1977er** [comment]
I will go with 2) and close this issue on thursday if noone raises an objection.

**Comment by 1977er** [comment]
Schnell schließen, bevor die 100 TB geliefert werden.
