### ISSUE TITLE
Add Zabbix routing template

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#122]

**Comment by 1977er** [comment]
- re-use MTR template
- evaluate rewrite of externalscript usage
- discover /etc/iproute2/rt_tables

**Comment by lemoer** [comment]
I added the milestone "Beginn der stabilen Phase", as this contains useful monitoring and should therefore implemented before the "stabile Phase".

**Comment by AiyionPrime** [comment]
As i obviously missed out on a fun night?
Is 'stabile Phase' a regualr goal or an ever pending milsestone from now on, to which each and every issue is added? :D

**Comment by lemoer** [comment]
There is a mail-thread "Stabiltität der Infrastruktur: Problemlösephase,
dann stabile Phase?" on intern@, explaining the idea.

The milestone is suggested to be terminated to Sunday evening (2020-02-08).

**Comment by AiyionPrime** [comment]
Thanks. I'm excited to find out, how well milestones work for us.

**Comment by 1977er** [comment]
I will try to implement that into the routing template. ;)

**Comment by 1977er** [comment]
Ach, kann weg.
