### ISSUE TITLE
gateway_announcement.sh depends on deprecated /sys/class/net/bat

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#124]
/sys/class/net/bat was removed in batman-2021.

**Comment by AiyionPrime** [comment]
Likely not -.-'
/sys/class/net/bat/**bat_related-stuff** is.

**Comment by AiyionPrime** [comment]
just asked #batman to be sure...

> 22:26:21     aiyion | even in 2021.0 /etc/sys/class/net/bat0/operstate does still work, right? That's nothing that's meant by "2021.0 has no sysfs support anymore"?

Antwort steht noch aus;
je länger ich über operstate nachdenke, umso eher gehe ich davon aus, dass das vom Treiber implementiert werden muss.

**Comment by AiyionPrime** [comment]
#wontfix apparently no need...
