### ISSUE TITLE
gateway_announcement.sh depended on removed dhcpd

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#126]
dhcpd was the service file of the isc server, which was removed before kea was rolled out.

The new kea role should have added its own service, which either is just called differently or has not been roled out on sn09 and sn07 for some reason.

This became only clear, after sn09 was deployed tonight, as on sn07 the crontab has been altered in joyful expectation of #124.

This is linked to #113.

**Comment by AiyionPrime** [comment]
I just looked for references, where it works,
SN01 is not a good example:

```
Feb 05 05:16:01 sn01 systemd[1]: Starting Kea DHCP Server for IPv4 (kea-dhcp4.conf)...
Feb 05 05:16:01 sn01 systemd[1]: Started Kea DHCP Server for IPv4 (kea-dhcp4.conf).
Feb 05 05:16:01 sn01 kea-dhcp4[26249]: 2021-02-05 05:16:01.328 INFO  [kea-dhcp4.dhcp4/26249.140380574933760] DHCP4_STAR
Feb 05 05:16:01 sn01 kea-dhcp4[26249]: kea-dhcp4 already running? Daemon::createPIDFile: PID: 12005 exists, PID file: /
Feb 05 05:16:01 sn01 kea-dhcp4[26249]: 2021-02-05 05:16:01.332 FATAL [kea-dhcp4.dhcp4/26249.140380574933760] DHCP4_ALRE
Feb 05 05:16:01 sn01 systemd[1]: dhcpd.service: Main process exited, code=exited, status=1/FAILURE
Feb 05 05:16:01 sn01 systemd[1]: dhcpd.service: Failed with result 'exit-code'.
```

**Comment by AiyionPrime** [comment]
On sn08 and sn10 the ISC server is still running.

**Comment by AiyionPrime** [comment]
The new kea dhcp role indeed does setup a service which is called differently than dhcpd as of f918f1883c81652c6846f07ec617f17abf645743.

I hotfixed this on sn07 and sn09 but the next roleout of master of us will break things again.
(lemoer codefetch please see this)

This is rather urgent, please reconsider the service name, or give good reason why to keep calling it differently than dhcpd.

It's nice that on eof our scripts depended on this, I have no clue what else expects the dhcpd service to be called dhcpd.

**Comment by AiyionPrime** [comment]
I just added the hotfix to master; in case you decide on changing the service name back to dhcpd the commit to revert is 6c585123a8c4d813ad9e0a10e94c63b29883818f

**Comment by AiyionPrime** [comment]
Feel free to close once you decided on how to name the service, @1977er :)

**Comment by 1977er** [comment]
Sorry for the trouble. I wasn't aware of that dep in gateway_announcement. I want to go with the name chosen by Debian.

**Comment by AiyionPrime** [comment]
No worries.
