### ISSUE TITLE
ffh.kea-dhcp4-server lacks readme and documentation

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#127]
Debugging this role just became a joy, as the documentation is not yet available :S
Please consider at least a readme.

**Comment by 1977er** [comment]
There was one for the predecessor? ;-)

**Comment by AiyionPrime** [comment]
Well, kind of shitty, but yes -.-'
https://github.com/freifunkh/ansible/blob/master/docs/dhcp_server.md

Your new readme is way better, thanks!
