### ISSUE TITLE
export_batman.sh depends on deprecated /sys/class/net/bat

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#132]
ffh.zabbix-agent/files/etc/zabbix/bin/export_batman.sh

```for batdev in /sys/class/net/bat*; do```

**Comment by CodeFetch** [comment]
https://www.open-mesh.org/attachments/857

**Comment by AiyionPrime** [comment]
@CodeFetch I'll promise to grab a coffee right now, to increase speed on my end a little;
but where do you want this helper script to be used exactly?

**Comment by CodeFetch** [comment]
@AiyionPrime I think actually batctl should have a possibility to list the interaces. This was only thought as a reminder we could do implement it this way... I think the awk-solution is fine.
