### ISSUE TITLE
kea wants to run on bat0

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#133]
I found this one on sn07:

Feb 05 06:29:04 h2879555.stratoserver.net kea-dhcp4[26946]: ERROR [kea-dhcp4.dhcp4.140388019499776] DHCP4_PARSER_FAIL failed to create or run parser for configuration element interfaces-config: Failed to select interface: interface 'bat0' doesn't exist in the system (/etc/kea/kea-dhcp4.conf:9:41) (/etc/kea/kea-dhcp4.conf:9:25)

There should be some check, whether the server kea is running on, even has dom0 support.

**Comment by 1977er** [comment]
@AiyionPrime This role honors the dom0_legacy variable. If it is set true, kea is working as expected. I cannot check the vars due to missing sn07 files in the repository.

**Comment by AiyionPrime** [comment]
Will look into that soon.

**Comment by AiyionPrime** [comment]
legacy_dom0 was true in my host file, no clue since when, or why.
Possible, that I misread read from day one as "interpret dom0 as legacy"=true
sn07 gets a new master run right now.

**Comment by AiyionPrime** [comment]
done
