### ISSUE TITLE
Start using ansible-lint

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#134]
```
┌─[okrueger@home] - [~/freifunk/ansible] - [Sat Feb 06, 11:11]
└─[$] <git:(master*)> ansible-lint playbooks/supernodes.yml
WARNING  Listing 268 violation(s) that are fatal
...
```

**Comment by 1977er** [comment]
Also see: https://xkcd.com/1285/

**Comment by AiyionPrime** [comment]
mhm, sounds interesting enough, I think.

Would help qcodefetch to make points about capitalization of task descriptions, I suppose.

Anything you'd really like to tackle with this?
Or do we just have to little to do? :D

**Comment by 1977er** [comment]
Tackle bad habits before they arise.

**Comment by AiyionPrime** [comment]
Not convinced, yet.
I always assumed our standard is "if it works, it works."

**Comment by AiyionPrime** [comment]
What about the others? Do you want roles linted, or not?

**Comment by 1977er** [comment]
Has not been picked up for over a year. Closing.
