### ISSUE TITLE
Restructure variables/secrets

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#136]
Status quo:
- group_vars/all.yml is grown big
- secrets.yml is used in every playbook and seems lost on the / directory level

Actions:
- reintegrate "secrets" in "all"
- split up groups_vars/all.yml

**Comment by 1977er** [comment]
FYI: @lemoer @CodeFetch @AiyionPrime @ctandi and anyone else.

**Comment by AiyionPrime** [comment]
Come on -.-'
I've got a shitload of shell scripts lying around which are now all matter to 'enhance'...
Maybe we talk a little longer about stuff that 'restructures', than twenty minutes in the middle of the day, before implementing such changes. This kind of stuff becomes the most irritating part of our whole repo.

**Comment by 1977er** [comment]
Shall I revert?

**Comment by AiyionPrime** [comment]
I don't think so.

**Comment by 1977er** [comment]
Can I help to update your scripts?

**Comment by AiyionPrime** [comment]
No thanks, will be fine.
