### ISSUE TITLE
automatic dry-run

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#145]
@lemoer 
> Wir sollten dringend dieses automatische Dry-Run von ansible für weniger Überraschungen implementieren.

Originally referenced in #93 

If someone could elaborate why and what is to do?

**Comment by lemoer** [comment]
There is no automatic rollout yet.

**Comment by lemoer** [comment]
> If someone could elaborate why and what is to do?

Some work has been done already:
- I created the script `tests/run.sh`:
    - It performs a **dry run** of *playbooks/supernodes.yml* and stores the result in `tests/tmp/$current_timestamp.json`.
    - You can try to run it on your own.
- I created three scripts to evaluate the results:
    - `tests/ls_roles.py`
        - Lists executed *roles* and the time in seconds it took to execute them.
        - Example output: [Link](https://paste.irrelefant.net/ooLeihu5.txt)
    - `tests/ls_tasks.py`:
        - Lists executed *tasks* and the time in seconds it took to execute them. (Finer resolution in contrast to `tests/ls_roles.py`)
        - Example output: [Link](https://paste.irrelefant.net/usou6Ohc.txt)
    - `tests/read_play.py`:
        - Prints all changed tasks in the usual ansible format:
            - Diffs are shown.
            - Colors are shown.
        - Unchanged tasks are omitted (in contrast to ansibles usual behavior).
        - Example output: [Link](https://paste.irrelefant.net/Vahdee3E.html)

I think, it would be fairly easy to install a cronjob somewhere to run these scripts periodically or so.

We could ...:
- ... run things periodically?
- ... maybe after each git push?
- ... send the output of `tests/read_play.py` automatically to monitoring@hannover.freifunk.net?
- ... ?

**Comment by 1977er** [comment]
In general this is up and running on ruettgers already. Maybe that host needs a new home with a stable IP address soon'ish.
