### ISSUE TITLE
respondd not running on sn01 

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#146]
I just saw this in the log: 
```
Feb 13 20:53:18 sn01 respondd.py[825]: usage:
Feb 13 20:53:18 sn01 respondd.py[825]:       respondd.py -h
Feb 13 20:53:18 sn01 respondd.py[825]:       respondd.py [-f <configfile>] [-d <dir>]
Feb 13 20:53:18 sn01 respondd.py[825]: respondd.py: error: unrecognized arguments: -i bat10 -b bat10 -i mesh_fastd_10 -i bat11 -
```

**Comment by AiyionPrime** [comment]
Somebody appears to updated meshannounce to the new configformat.
I can fix this, but do not know when.

**Comment by AiyionPrime** [comment]
@lemoer @1977er should this still have legacy domain support?

**Comment by lemoer** [comment]
Yep, please keep it till we officially drop the legacy support.

Am So., 14. Feb. 2021 um 11:36 Uhr schrieb J. Burfeind <
notifications@github.com>:

**Comment by AiyionPrime** [comment]
fine
