### ISSUE TITLE
stats: dhcp chart broken

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#152]
On https://stats.ffh.zone/d/jdRuYDYWz/supernodes-splitted the dhcp chart claims to plot the number of active leases. In fact it shows the number of all issued leases. It has to be reduced by the number of reclaimed leases.

active leases = cumulative-assigned-addresses - reclaimed-leases

**Comment by lemoer** [comment]
I added the milestone "Beginn der stabilen Phase", as this contains useful monitoring and should therefore implemented before the "stabile Phase".

**Comment by lemoer** [comment]
Fixed in 16d6c83d15b64637781f017d843a2aa536035640.

**Comment by lemoer** [comment]
Apparently this is still broken. sn10 has currently "-91" leases... The calculation "cumulative-assigned-addresses - reclaimed-leases" is broken...

**Comment by lemoer** [comment]
Let's define this as 'nice to have' and remove it from the milestone again.

**Comment by 1977er** [comment]
Abandoned a long time ago.
