### ISSUE TITLE
ffh.supernode contains warning

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#160]
`ffh.supernode : Adjust netfilter conntrack table size`

contains a warning about string conversion

**Comment by lemoer** [comment]
Who is causing the warning? What is the exact warning?

**Comment by AiyionPrime** [comment]
As I said, within ffh.supernode, the task 'Adjust netfilter conntrack table size'.

> [WARNING]: The value "1048576" (type int) was converted to "'1048576'" (type string). If this does not look like what you expect, quote the entire value to ensure it
> does not change.
