### ISSUE TITLE
Add Zabbix trigger on sudden Fastd connection loss

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#164]
Gerade ist die Gesamtzahl aller Fastd-Verbindungen gedroppt:
![Screenshot from 2021-02-20 18-47-13](https://user-images.githubusercontent.com/601153/108604117-117e6f80-73ac-11eb-9569-3c34d1a93104.png)

Können wir darauf einen Trigger setzen, damit das schneller auffällt? Als Trigger-Limit würde ich 900 vorschlagen.

**Comment by AiyionPrime** [comment]
ist 'gerade' als 1977er und ich sn01 getreten haben?

**Comment by 1977er** [comment]
Den Trigger habe ich mir auch schon gewünscht, aber der läßt sich mit Zabbix nur sehr unschön umsetzen: Wenn ich die Domänen dynamisch discoveren lasse, kann ich leider keine sog. Calculated Items über eine dynamische Menge an (discovered) Items machen. Die unschöne Umsetzung wäre eine hartkodierte Summierung über alle "jetzt bekannten" Domänen.

**Comment by lemoer** [comment]
@AiyionPrime Ja. Das Problem ist aber nicht so schlimm.  Sn01 ist dem telegraf/influx geflogen, da sich seine IP geändert hat. Wir filtern auf harvester die Influx-Verbindungen nach Quell-IP. Deshalb gab es auch keine Statistiken für sn07.

**Comment by lemoer** [comment]
Ok, sn01 ist nun wieder im Monitoring, nachdem ich harvester neu gerollt habe.

**Comment by lemoer** [comment]
I added the milestone "Beginn der stabilen Phase", as this contains useful monitoring and should therefore implemented before the "stabile Phase".

**Comment by 1977er** [comment]
Zabbix holt sich die Gesamtzahl der Verbindungen jetzt hier rüber ab:
`fastd`: `/usr/bin/ffh_peer_counter.sh -j | jq ".[] | .peer_count"`
`wireguard`: `sudo /usr/bin/ffh_wg_stats.py -i `ip -j link show type wireguard | jq -r ".[] | .ifname" | xargs` | jq ".[] | .established_peers_count" | awk '{s+=$1} END {print s}'`

Von meiner Seite ist das Issue damit erledigt. @lemoer, falls Du noch etwas entsprechendes für Grafana/Influx machen willst, kannst Du das gerne tun. ;-)
