### ISSUE TITLE
Improve KeepitUp Robustness 

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#167]
Steps:
- [x] Check if we can use the `online` information from the nodes.json instead of pinging by ourselves. Check this by taking a node offline and observing the behavior in the nodes.json.
- [x] Check what happens if we take a supernode offline for ~10 minutes.
- [x] Implement using the nodes.json instead of pinging.

**Comment by lemoer** [comment]
@moridius You mentioned, you maybe want to contribute. Therefore I assigned you as well.

**Comment by lemoer** [comment]
I'll focus on #166 first, I guess.

**Comment by AiyionPrime** [comment]
Remember, an awful lot of nodes.json related code is already implemented in nodesTk.
Adding it as library should make task 3 a lot easier.

**Comment by lemoer** [comment]
The main problem with KeepItUp is when supernodes are restarted or are unavailable due to maintenance. As this SHOULD NOT happen in the infrastructure freeze week, the current issues should not occur during that week anyways. I'll remove them as blocker from the milestone therefore.

However, some development has been done by @moridius and me. We'll deploy this after the infrastructure freeze week.

**Comment by lemoer** [comment]
The information if a node is online is now taken from the nodes.json. This should make the service a lot more robust against routing problems on the supernodes. Closing.
