### ISSUE TITLE
mesh.fastd breaks first run

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#169]
The zabbix user is not present in first the first run.
The zabbix user should have been created, before its assigned any files.

> TASK [ffh.mesh_fastd : Install Zabbix userparameter file] **************************
> fatal: [sn05]: FAILED! => {
>     "changed": false,
>     "checksum": "7b1be2479ec68d08ac0b108b9abc2712fa038d28",
>     "gid": 0,
>     "group": "root",
>     "mode": "0644",
>     "owner": "root",
>     "path": "/etc/zabbix/zabbix_agentd.d/userparameter_fastd.conf",
>     "size": 392,
>     "state": "file",
>     "uid": 0
> }
> 
> MSG:
> 
> chown failed: failed to look up user zabbix

@1977er this one looks like yours.
@CodeFetch this broke ferm again. We'll need an open firewall again...

**Comment by CodeFetch** [comment]
@AiyionPrime Nice and clean again. That's why I wanted to start automatizing it... So I'll give you a user without a shell on the hypervisor which can issue commands to backup, delete and create new ones later...

**Comment by 1977er** [comment]
Oh, nice catch. I have to come up with an alternative user, if zabbix is not installed yet. Will work on it when I get back home later this evening.

**Comment by AiyionPrime** [comment]
Thanks your two

**Comment by CodeFetch** [comment]
Solved by @1977er.
