### ISSUE TITLE
Add role 'meshviewer'

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#187]
I just saw, we already have got an nginx role, I suppose the next step would be to add a meshviewer role, that builds up on it.

The last change appears to be from last years august, as a locale file was added; I don't think this is urgent, but being able to role this via ansible appears to be nice and may make patching meshviewer easier in the future.

**Comment by AiyionPrime** [comment]
What he have is still a upstream ffrgb meshviewer? Or do we run a fork?

**Comment by 1977er** [comment]
Done.
