### ISSUE TITLE
Add zabbix trigger for missing supernode <-> supernode links

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#191]
The output of `batctl n -H | grep vlan-gt | wc -l` should be equal to `N-1`, where `N` is the number of supernodes we have.

@1977er Can you add a zabbix trigger for this?

**Comment by lemoer** [comment]
Hm, of course, this should be done for all domains individually... :/

**Comment by 1977er** [comment]
This makes "maintenance" a little bit more difficult. Have to think about it.

**Comment by 1977er** [comment]
`batctl meshif batXX n -H | grep vx-cross | wc -l` since we moved from vlan-gt to vxlan.

**Comment by 1977er** [comment]
Added triggers in Zabbix Batman Template.
