### ISSUE TITLE
rfc: nextcloud for core team?

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#194]
With every year our need to organize and manage things tends to rise.
And with it our need to put an excel sheet, or a bunch of pictures anwhere.

Apparently the wiki is not a natural destination for these media.
Furthermore not all of us are so nimble with the console, that storing the files anywhere on webservers by hand would be feasible, either.

As I feel a growing anger about us putting our info in google clouds and drives, I'd like us to have a nextcloud.
The Interface is intuitive and rather clean, it supports plugins for all sorts of excel sheets and presentations and we really should not have a problem sorting this out fast.

@bschelm Sharing files with a link works just as easy as in google drive.

**Comment by bschelm** [comment]
Yes, please :-)

**Comment by 1977er** [comment]
Then, it’s settled. :-)

**Comment by AiyionPrime** [comment]
@1977er I suspect I'll be us setting this up. There are numerous ansible roles in the galaxy for this; or do you really intend to use docker for this?

**Comment by 1977er** [comment]
We use Syncthing (for FNorden stuff) now.
