### ISSUE TITLE
nsd: hannover.freifunk.net zonefile missing

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#202]
Since - I don't know when - the `hannover.freifunk.net` zonefile is not generated (anymore). Currently a copy from zones_old directory fills the gap.

@Manawyrm Help. ;-)

**Comment by Manawyrm** [comment]
Yeah, that's an interesting problem :) 
It probably only surfaced when I renamed "zones" to "zones_old" (to make sure everything was cleared), but nsd seems to have cached everything until your restart recently. 

Here's the interesting part: 
There's no zonefile/configuration for hannover.freifunk.net anywhere in the Ansible :smile: 
There is a configuration to use `zonefile: "hannover.freifunk.net.zone"`, this specific zonefile in the nsd-config, but the file is nowhere to be found.

Should we just convert the hannover.freifunk.net.zone file to some ansible/yaml lines?

**Comment by 1977er** [comment]
Yes, please. I failed trying to do so. ;-)

**Comment by Manawyrm** [comment]
I've created a pull request (and I've deployed it on ns1).

**Comment by 1977er** [comment]
Ah, when I tried to do so, I missed to purge hannover from `dns_authoritative_external`.

**Comment by 1977er** [comment]
@Manawyrm 

`@           IN  MX 10 mail` should be `@           IN  MX 10 mail.ffh.zone.` Currently mail delivery is broken.

Why do these end up in hannover.freifunk.net?

```
; Statische Hosts (aus der Ansible-Konfiguration)
pve-ffnw.hannover.freifunk.net. IN  AAAA 2001:678:978:ff01::1
sn01.s.hannover.freifunk.net. IN  AAAA 2001:678:978:ff01::2
rdns.hannover.freifunk.net. IN  AAAA 2001:678:978:ff01::3
```

**Comment by 1977er** [comment]
Nothing to do here (anymore). Closing.
