### ISSUE TITLE
mesh-announce

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#206]
`mesh_fastd_0,vlan-gt-20,vx-0` should be `Interfaces: mesh_fastd,vlan-gt-20`.

**Comment by 1977er** [comment]
That makes it harder to generate interfaces names in loops.

**Comment by AiyionPrime** [comment]
If you think this way around is wrong, we can rename `mesh_fastd` to `mesh_fastd_0`, but I think that would be a bigger effort.

Technically it *is* already harder to generate interfaces names in loops.correctly,
we are just not doing it there yet, which might or might not result in unexpected behavior,
depending on the implementation of mesh-announce.

**Comment by AiyionPrime** [comment]
resolved in 935877c04e53ebc055cfc71163a6bc06868ab22e
