### ISSUE TITLE
mesh-announce does not listen on vlan-gt-20

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#207]
For whatever reason, mesh-announce does not listen on `dom0`s vlan-gt interface.

**Comment by 1977er** [comment]
By choice. We do not offer wireguard for the legacy domain. As far as I know it is not possible (except bruet force) to put a recent firmware into the legacy domain.

**Comment by AiyionPrime** [comment]
I'm not sure what you are talking about.
I am talking about `vlan-gt-20` an interface, that's created in `roles/ffh.supernode/tasks/gt.yml`.
Do you talk about the (not existing) `vx-0`?

I need to read up, what vlan-gt was for again, but I think its part of connecting supernodes with each other, not wireguard.

**Comment by 1977er** [comment]
My mistake. You are right.

**Comment by lemoer** [comment]
> I think its part of connecting supernodes with each other, not wireguard.

Yep. The packages travel along the following path: `bat0 -> vlan-gt-20 -> br-gt -> gt-sn01 -> eth0`. This means that the batman packages are encapsulated in a vlan before being sent to the gretap interface. As gretap does not provide a multiplexing capability like "tcp port" or "udp port", this is our way to transport multiple domains over gretap.

**Comment by AiyionPrime** [comment]
No problem @1977er :)
