### ISSUE TITLE
nightly v6 only

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#211]
The server build.ffh.zone provides `http://build.ffh.zone/job/gluon-nightly/ws/download/images/sysupgrade/nightly.manifest` but does not have a v6 address.

The autoupdater of mesh-only nodes can therefore not connect to it.

One possible solution would be to reeneable v6 on the buildserver, which is unavailable since 14 months.
https://github.com/freifunkh/ansible/commit/4c23668902c6e2a99ddeac42c0b9059773e0f656

The other one could be a proxy on firmware.ffh.zone.
Having a transparent proxy for the nightly path to the build server would not be the prettiest but likely a more stable solution.

Any other suggestions?

Thanks for the feedback!

**Comment by lemoer** [comment]
This is not true anymore, I think:
``` 
lemoer@orange ~> host build.ffh.zone
build.ffh.zone has address 130.75.178.26
build.ffh.zone has IPv6 address 2001:678:978:214::baba
```
