### ISSUE TITLE
Daily CI runs

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#213]
@1977er is spending a VM, where we can do our daily CI runs.

Tasks:
- [x] Create script to run playbooks (Done in f2a127125d4328d8b90f2d9668a79ca65e53e055)
- [x] Create script to read play results from json (Done in f2a127125d4328d8b90f2d9668a79ca65e53e055)
- [x] Redact secrets using diff=False. (Done in 007bde515836406a30726a3b5a2f9e5891957514)
- [x] Only redact secrets, when playbooks are run via tests/run.sh (Done in 8f0326f1d18433f082850c630e77dc7fdf3aeac3)
- [x] Stabilize loop order (Done in 7daeb3dea3717a47bbc8306c59fd47419a255c22)
- [x] Create a script to send (html&plain) mails. (Done in 416d356f745c83ca492e436cf238c4a264319bf0)
- [x] Create a VM.
- [x] Deploy the scripts.
- [x] Setup cronjob.
- [x] Avoid sending mails if there are no changes. (Done in 7cd808e)
- [x] Stabilize roles/playbook so no unnecessary changed states occur. (Done in c000b15)

I would suggest that we start with the supernodes.yml playbook first and add others afterwards.

**Comment by 1977er** [comment]
Deployed on ruettgers.ffh.zone (former Forschungsminister). Run multiple playbooks, not just supernodes. Output is on the monitoring list.
