### ISSUE TITLE
Monitor If Router IPs are Reachable

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#216]
Sometimes due to routing issues or radv issues, some of these addresses 

![Screenshot from 2021-09-11 00-48-17](https://user-images.githubusercontent.com/601153/132925462-f27d5028-fbd3-4aae-a18d-c14950305867.png)

become unreachable...

I would suggest to monitor them with Zabbix.

**Comment by lemoer** [comment]
`
curl https://harvester.ffh.zone/nodes.json | jq -r '.nodes[] | select( .nodeinfo.hostname == "perf-test") | .nodeinfo.network.addresses[]' | grep -e '^2'
`

**Comment by lemoer** [comment]
Next level:
```
curl -s https://harvester.ffh.zone/nodes.json | jq 'def lpad(n):tostring |if (n > length) then ((n - length) * "0") + . else . end; [.nodes[] | select( .nodeinfo.hostname == "perf-test") | .nodeinfo.network.addresses[] | select(. | startswith("2")) | { "peeraddr": ., "supernode": ("sn"+(. | split(":") | .[3] | sub("99$";"") | lpad(2))) }]'
```

**Comment by 1977er** [comment]
Would pinging hard coded IP addresses be such a bad idea? (But hey, cool jq expression.) :-D

**Comment by lemoer** [comment]
This is already implemented in the Zabbix Template "FF Statuspage Reachability" (see here: https://zabbix.ffh.zone/templates.php?form=update&templateid=10342)
