### ISSUE TITLE
dns_zonenodes: support meshviewer format v2

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#22]
I currently have a setup, where meshviewer v2 format is used. Maybe this patch could be useful somewhen in future...

``` patch
--- knoten_compile.pl	2017-02-25 02:34:58.274837705 +0000
+++ knoten_compile.pl.bak	2017-02-25 02:36:36.749872556 +0000
@@ -66,15 +66,15 @@
 
     # Get hostname and IPv6 address from nodes.json
     # normalize hostname
-    foreach my $node ( @{ $data->{nodes} } ) {
+    foreach my $node_id ( keys %{ $data->{nodes} } ) {
         my $ip;
         my $names;
-        foreach my $node_ip ( @{ $node->{nodeinfo}->{network}->{addresses} } ) {
+        foreach my $node_ip ( @{ $data->{nodes}->{$node_id}->{nodeinfo}->{network}->{addresses} } ) {
             next if $node_ip !~ m/^2a06/;
             $ip = $node_ip; 
         }
         next unless $ip;
-        my $hostname = normalize_nodename( $node->{nodeinfo}->{hostname} );
+        my $hostname = normalize_nodename( $data->{nodes}->{$node_id}->{nodeinfo}->{hostname} );
         
         if ($mode eq "forward")
         {
```

**Comment by lemoer** [comment]
Filter out next node adresses:
- `next if $node_ip =~ m/^2a06:8187:fbab:2::1/;`

**Comment by 1977er** [comment]
What kind of prefix is 2a06:/112?

**Comment by lemoer** [comment]
Am 25. Februar 2017 11:58:58 MEZ schrieb "Oliver Krüger" <notifications@github.com>:
>What kind of prefix is 2a06:/112?

This is just an example for a next-node address.

I'm currently using the script also for the `babelnetz.ffh.zone.` zone in the gluon babel branch. The IPs are actually from freifunk frankfurt, because I'm testing with their firmware.

You could take a look at http://lemoers-testbox.babelnetz.ffh.zone/ :wink:

**Comment by lemoer** [comment]
Think it's done.
