### ISSUE TITLE
harvester: nginx startup fails when dns is not ready

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#222]
After a reboot the name resolving mechanism might start after nginx. Then the following lookup fails and the whole nginx dies:

`nginx: [emerg] host not found in upstream "downloads.openwrt.org" in /etc/nginx/sites-enabled/opkg.ffh.zone:19`

**Comment by 1977er** [comment]
Da ist bereits eine Indirektion eingebaut, deren Syntax mir unbekannt ist:

```
upstream osm_tiles {
    server a.tile.openstreetmap.org;
    server b.tile.openstreetmap.org;
    server c.tile.openstreetmap.org;
    keepalive 16;
}
...
proxy_pass http://osm_tiles;
```
Dass da nicht einmal ein Dollarzeichen steht, finde ich komisch, aber ich kenne die Syntax von nginx auch nicht so. @Suuush meinst Du, eine weitere Indirektion über Variablen für a, b und c würde hier noch etwas bringen?

**Comment by Suuush** [comment]
Ich dachte das Problem tritt nur mit opkg (openwrt, lede, modules) auf Harvester auf?
Dann sollte es diese Stelle sein:
```
    location /openwrt/ {
        proxy_pass          http://downloads.openwrt.org/;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
    }
```
Ich kann mir das am Donnerstag mal anschauen:
https://github.com/freifunkh/ansible/blob/f81557e39133bea2388fe6fcdb9c056afe53922c/roles/ffh.nginx/templates/05-nginx-site-location.j2#L10

**Comment by AiyionPrime** [comment]
Können bestätigen, das Problem exisiert noch.

**Comment by 1977er** [comment]
Fixed with 4a8dd087b77f2361c52c32a8e547ec48908fc1f8

**Comment by AiyionPrime** [comment]
the dns "resolver" from he was in fact an authorative dns server, that served 'refused' for about everything not coming from HE.
