### ISSUE TITLE
wireguard config zu offen

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#223]
/etc/systemd/network/30-wg-10.netdev has 0644 mode that is too permissive

**Comment by 1977er** [comment]
Well, the private keys... I will test, if 0640 or even 0600 is fine with systemd.

**Comment by 1977er** [comment]
Testing on sn05 with manual changes: setting to 0640 (root:root). If it doesn't burn within the next hour, I will make it persistent.

**Comment by 1977er** [comment]
Closing it for now.

**Comment by 1977er** [comment]
No, can't do. systemd-networkd fails to create wg interfaces in case of `0640`. Reverting back to `0644`.
