### ISSUE TITLE
Introduce time offset for peer repo updates on supernodes

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#239]
Idee aus dem 3Ländereck:
Die Gateways versetzt pullen lassen. Jedes weiter nur alle Minute/alle 5 Minuten,
aber nicht alle auf volle 5 Minuten.

Entweder wir machen das über die syntax, die das random macht, oder lassen das nach supernode identifiern und modulo shiften, sodass weiterhin leicht ersichtlich ist, was als nächstes passieren wird.

danke an @kpanic

**Comment by 1977er** [comment]
Welches Problem soll das lösen?
