### ISSUE TITLE
bullseye: kea 1.8 unavailable

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#241]
isc-kea-dhcp4-server is not available in debian bullseye on the 1.8 branch.

We'll need to update it to version 2.

**Comment by 1977er** [comment]
Installed 2.2 on sn01 via ansible. Needs further testing.

**Comment by 1977er** [comment]
All supernodes are migrated to bullseye and kea 2.2. No smoke detected so far. Closing.
