### ISSUE TITLE
ferm: table defined twice

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#242]
In https://github.com/freifunkh/ansible/blob/master/roles/ffh.supernode/templates/ferm.mark.conf.j2 table `mangle` is defined twice leading to a syntax error.

**Comment by AiyionPrime** [comment]
introduced in 5943889809b4f6f8216c0b49aa6713e16dbab151

**Comment by AiyionPrime** [comment]
We should keep an eye out for weird routing/traffic issues, now that ferm does something different than before ;)

**Comment by 1977er** [comment]
It won't. The rule was accepted before. The ferm parser seem to be quite forgiving.

**Comment by AiyionPrime** [comment]
As long as the accepted rule did mean the same as the now accepted rule does.
