### ISSUE TITLE
Grafana board not loading

### ISSUE THREAD

**Issue by g3n35i5** [freifunkh/ansible#255]
The grafana dashboard for the [voraus robotik](https://stats.ffh.zone/d/EGysRPsMz/router-fur-meshviewer?var-node=42915c3f8735&from=now-12h&to=now-1m&orgId=1) node is not loading.

@AiyionPrime ping

**Comment by AiyionPrime** [comment]
504 on the query. Maybe @1977er has an idea.
Next step would be to reproduce it outside of work.

**Comment by 1977er** [comment]
Looks like a InfluxDB Timeout. No idea, how to debug. I think @lemoer built these dashboards.
