### ISSUE TITLE
nginx: dhparam generation takes really long

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#27]
This is especially annoying on virtual machines, because there is not a lot of randomness. Maybe we should simply use `-rand /dev/urandom`.

**Comment by mweinelt** [comment]
https://wiki.mozilla.org/Security/Server_Side_TLS#Pre-defined_DHE_groups

**Comment by 1977er** [comment]
@Suuush What about "conditionally use pre-calculated DH groups" in the role?
