### ISSUE TITLE
dns_recursive: unbound sometimes fails to start at boot

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#28]
> -- Logs begin at Sa 2017-03-18 04:24:52 CET, end at Sa 2017-03-18 04:30:01 CET. --
> Mär 18 04:24:52 gw03 systemd[1]: sockets.target: Job sockets.target/start deleted to break ordering cycle starting with basic.target/start
> Mär 18 04:24:52 gw03 systemd[1]: rpcbind.service: Job rpcbind.service/start deleted to break ordering cycle starting with basic.target/start
> Mär 18 04:24:52 gw03 systemd[1]: Failed to start Fast and Secure Tunnelling Daemon (connection fastd_mesh).
> Mär 18 04:24:52 gw03 kernel: batman_adv: bat0: Not using interface mesh_fastd (retrying later): interface not active
> Mär 18 04:24:54 gw03 systemd[1]: Failed to start unbound.service.

Seen so far on sn03 and sn09 within a couple of days.

**Comment by Suuush** [comment]
b025c6b introduces a 5 second delay to dns_recursive and radv_server.

**Comment by 1977er** [comment]
Did not occur in the last couple of months.
`parallel-ssh -ih freifunk/supernodes.txt "ps ax | grep -e '[u]nbound'"` shows no irregularities.

Silently closing.
