### ISSUE TITLE
Role "yanic" is incomplete

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#29]
The role does not:
- Clone and install the yanic binary
- Maybe we want to apply some additional patches:
    - https://paste.irrelefant.net/Utae3ahw.txt

**Comment by AiyionPrime** [comment]
What about filling the todo with the default build line?
go get -v -u github.com/FreifunkBremen/yanic

**Comment by 1977er** [comment]
Can this be closed?

**Comment by 1977er** [comment]
Can this be closed?

**Comment by lemoer** [comment]
Doesn't seem so: https://github.com/freifunkh/ansible/blob/master/roles/ffh.yanic/tasks/main.yml#L34

**Comment by 1977er** [comment]
@Suuush Whats the blocker?

**Comment by AiyionPrime** [comment]
@lemoer your referenced paste expired. Have we got that one anywhere else?

**Comment by Suuush** [comment]
I hope we don't need any patches.
One for https://github.com/FreifunkBremen/yanic/commit/00df010870506fee1176128b453f4edb35b6bc99 is no longer needed.

Does anyone have experience with a ansible module for golang packages?

**Comment by AiyionPrime** [comment]
I'm on it.

**Comment by AiyionPrime** [comment]
Sorry for not seeing your reply earlier @Suuush , the go part is already done,
the patch part s a little tricky, I'll put you on the review later :)
