### ISSUE TITLE
Error while  "Adjust netfilter conntrack table size"

### ISSUE THREAD

**Issue by eaxi** [freifunkh/ansible#3]
TASK [simple_firewall : Adjust netfilter conntrack table size] *****************
fatal: [sn04]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to reload sysctl: sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: Datei oder Verzeichnis nicht gefunden\n"}
        to retry, use: --limit @/root/ansible/sn04.retry

**Comment by lemoer** [comment]
Hopefully this is now fixed. I'll leave this open for a while... We will see if this is really fixed, when we deploy the next supernode from bottom up.

**Comment by 1977er** [comment]
"a while" is over.
