### ISSUE TITLE
nginx: requires systemd but does not install it

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#31]
Silently assumes systemd is installed. This is usually the case since we heavily rely on networkd which installs systemd. But this is not generally the case.

**Comment by Suuush** [comment]
> [19.04.2017 18:23:26]  <@_1977er>	Sush: Sorry, hatte mich an dem Tag wohl etwas verrannt. Kann das mit systemd/nginx auch nicht mehr nachvollziehen.
