### ISSUE TITLE
simple_mail: hostname should not point to ansible_fqdn

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#37]
ssmtp.conf points to `hostname={{ ansible_fqdn }}` which may lead to unwanted hostnames on netcup or contabo machines.

Wanted hostname: snX.s.ffh.zone or the like.

**Comment by lemoer** [comment]
@1977er Did you try to fix it yet?

**Comment by 1977er** [comment]
Fixed the ssmtp config part, but apparently this is not sufficient. :-(
Postfix config on the MTA needs to be touched.
