### ISSUE TITLE
use babeld

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#39]
**exitnode:**

```
root@leintor:~# cat /etc/babeld.conf 
# For more information about this configuration file, refer to
# babeld(8)

interface gre-sn01 type wired

redistribute local deny
redistribute ip ::/0 src-prefix 2a02:790:ff::/56 le 1 metric 256

# status socket on port 33123 (tcp)
local-port 33123
```

**supernode:**

```
root@sn01:~# cat /etc/babeld.conf 

redistribute local deny

# status socket on port 33123 (tcp)
local-port 33123
```

**other stuff:**
- iptables rule for babeld udp traffic (port 6696)
- TTL stuff gre
- build babeld from source (at least on debian jessie)
- maybe add a service file or adjust interfaces in /etc/default/babeld 

**dump info:**

``` shell
echo "dump" | nc ::1 33123 -w 1
```

**Comment by lemoer** [comment]
source based routing seems to be insufficient in regard to source adress selection when sending icmp-hoplimit-exceeded packets (eg. when using traceroute).

so we use `ip rule` based routing

**exitnode:**
```
interface gre-sn01 type wired

redistribute local deny
redistribute ip ::/0 le 1 metric 256

local-port 33123
```

**supernode:**
```
export-table 42

redistribute local deny
redistribute ip 2a02:790:ff::/52 metric 256

local-port 33123
```

**more stuff needed**:
- ip6 rule is not existing yet
- fwmark for gre-leintor is not set
- sysctl net.ipv6.fwmark_reflect has to be '1'
- route to bat0 device has to be in routing table 42
- i think latest babeld is not necessary anymore

**Comment by 1977er** [comment]
@lemoer can this be closed?
