### ISSUE TITLE
Create role "dns_authorative"

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#4]
We should create a role to manage an authorative dns server to manage our ```ffh.``` and ```ffh.zone.``` zones.

I would prefer using ```nsd[1]``` (the companion of unbound) for it.

Questions:
- Should we generate the zonefile from ansible variables?
    - Until now the hostsfile (dnsmasq) is received from a seperate git repository via cronjob
        - I think this is undesirable, since errors are first noticed when the data is pushed and somewhen pulled by the cronjob (which then fails).
    - If we handle it directly with ansible, we could do a syntax check for the zone file directly while executing the role.

[1] https://www.nlnetlabs.nl/projects/nsd/

**Comment by Manawyrm** [comment]
Implemented in https://github.com/freifunkh/ansible/pull/5

Still missing is a good mechanism to parse the nodes.json and create AAAA records for all the individual routers.

**Comment by lemoer** [comment]
I think this is done and can be closed ;)
