### ISSUE TITLE
roles to migrate to multi domain

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#40]
- [x] mesh_fastd
- [x] mesh_fastd_remotes_backbone
- [x] mesh_fastd_remotes_peers_git
- [x] networkd konfiguration für die bat/mesh devices
- [x] dhcp_server
- [x] gateway_announcement
- [x] mesh_batman
- [x] radv_server
- [x] simple_firewall
- [x] yanic?
- [x] unbound

Variables:
- dns_recursive: ```{% for ip in dns_recursive_listen_on %}``` ?
- [x] networkd konfiguration für die bat devices.

**Comment by 1977er** [comment]
working on dhcp_server, checkin tomorrow after testing

**Comment by lemoer** [comment]
Lets handle the firewall stuff in a lazy and hacky way instead:

- Introduce a flag `firewall_is_multidomain_supernode`
- Implement the needed iptables commands directly in the templates for `/etc/iptables/rules.v{4,6}` instead of any abstraction.

Following things will be needed:
- [ ] incomming traffic: fastd: 10000-10100/udp
- [ ] incomming traffic allowed from bat0 (-i bat0): dns: 53/udp, dhcp: 67/udp, yanic: 1001/udp; iperf3: 5201/tcp
- [ ] frowarded traffic: allow forwarding between all: `bat*` and `internetz-me` and `internetz-me` (especially also batX <-> batY)
- [ ] any traffic (incomming and forward) from `bat*` should go to routing table "freifunk" (42). Previously is this feature known as `firewall_alternative_routingtables`

**Comment by 1977er** [comment]
magic happened in the meantime
