### ISSUE TITLE
mesh_announce: come to multidomain land

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#53]
Currently this role starts the respondd only on bat0.

**Comment by AiyionPrime** [comment]
I think the discussion at ffnords repo came to no conclusion, and won't unless we dont kick them :D

ecsv worked out a nice looking solution:
https://github.com/FreifunkVogtland/mesh-announce/commits/ffv

I think we should give it a shot and ask ffnord to merge it into upstream.
