### ISSUE TITLE
batman: use alternative version

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#6]
Maybe we should add a variable to choose an alternative batman version or git repo.
- This could be helpful, since the debian version is often very old.
- Maybe we should use the some of this [patches](https://github.com/freifunk-gluon/gluon/tree/master/patches/packages/routing)

**Comment by AiyionPrime** [comment]
I like the idea,
lets talk about this at lunch

**Comment by lemoer** [comment]
Working.
