### ISSUE TITLE
leintor: Migrate to new IPv6 address

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#62]
Due to sudden network changes the address 2a02:790:1:ff::1001 was assigned in a hurry.
This address might imply that the leintor is sn01 and can cause confusion.

Therefore a new address should be assigned.

prefix::1 and prefix::2 are taken and must not be taken.

**Comment by lemoer** [comment]
The fact is still correct. Leintor still uses `2a02:790:1:ff::1001` on eth0:
```
[root@leintor]:~ # ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:01:0b:b5 brd ff:ff:ff:ff:ff:ff
    inet 81.3.6.94/29 brd 81.3.6.95 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a02:790:1:ff::1001/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe01:bb5/64 scope link 
       valid_lft forever preferred_lft forever

```

I never got confused by this yet. Since nobody complained about this since over 2 years, this is closed now.
