### ISSUE TITLE
Implement all-knowing-DNS

### ISSUE THREAD

**Issue by Manawyrm** [freifunkh/ansible#63]
Further discussion about rDNS, the use of the ULA and maybe even dynamic/all-knowing-DNS is still needed.

See: https://apps.db.ripe.net/db-web-ui/#/query?bflag&searchtext=f.f.0.0.0.9.7.0.2.0.a.2.ip6.arpa&source=RIPE&types=rtr-set;domain#resultsSection

Currently 
nserver:         pns01.dcsix.net
nserver:         pns02.dcsix.net
nserver:         pns03.dcsix.net
nserver:         pns04.dcsix.net
are responsible for delivering a reverse-dns lookup for the IPv6-address block.
In theory, we could (and maybe should) create a NS record on these nameservers, which only redirect the  2a02:790:ff:7/64 to our nameservers, aka ns1.fnorden.net and slaves. 
We could then go from there and (for example) set up an all-knowing-dns. 

(this addresses the issues mentioned in https://github.com/freifunkh/ansible-configs/issues/20#issuecomment-288129495 )

**Comment by AiyionPrime** [comment]
This appears to be a bigger thing; do we want to meet up for this on an upcoming weekend?
I'd propose the sixth of march.

**Comment by Manawyrm** [comment]
> I'd propose the sixth of march.

Sounds good. I have a pretty okay Ansible role for all-knowing-dns, which will need a bit more generalization, but should work fine. 
We'll need a public IPv4 & IPv6 address and unused port 53, otherwise we'll need to reverse proxy the all-knowing-dns with another DNS server (which hasn't worked very well in my tests back then). 
Do we have a spare IPv4&IPv6 pair to run this or do we need some "creative" solutions? :smile:

**Comment by 1977er** [comment]
When do we start tomorrow?

**Comment by AiyionPrime** [comment]
Im free starting from 10:30.
@lemoer @Manawyrm ?

**Comment by AiyionPrime** [comment]
okay, then let's say 13:00?

**Comment by AiyionPrime** [comment]
@lemoer @Manawyrm ...

**Comment by Manawyrm** [comment]
> okay, then let's say 13:00?

fine by me. Mumble/IRC?
