### ISSUE TITLE
supernode: sys-subsystem-net-devices-vlan\x2dgt\x2d20.device.wants

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#71]
Eventuell wollen wir keine UTF8 Zeichen in Dateinamen/Devicenamen haben. Scheint zwar zu funktionieren, aber sieht nicht schön aus.

**Comment by lemoer** [comment]
This is out of our control. Systemd automatically creates those unit names if "-" characters are used in network interface names...
