### ISSUE TITLE
Create maintenance command

### ISSUE THREAD

**Issue by moridius** [freifunkh/ansible#73]
There should be a script available on every host to set that machine into maintenance mode in Zabbix (to disable alerting).

`> maintenance 30`
`System is in maintenance mode until 13:37.`

`> maintenance 0`
`System is no longer in maintenance mode.`

**Comment by moridius** [comment]
See https://github.com/freifunkh/ansible/blob/master/playbooks/maintainance_start.yml#L12

**Comment by moridius** [comment]
Script exists but needs to get integrated into our Ansible roles. See [zabbix-maintenance](https://github.com/freifunkh/zabbix-maintenance).

**Comment by AiyionPrime** [comment]
Whats left here?

**Comment by 1977er** [comment]
I think moridius intended to use his zabbix-maintenance tool in the ansible context. We are not doing this right now. Not sure if its needed there. I suggest closing this for now and re-open it when we have automatic ansible runs and get too much notification noise.

**Comment by AiyionPrime** [comment]
@moridius was asked to implement it by our zabbix users, iirc?
I don't think he intended usage very much, himself.

Maybe we should be using it more?
But sure, if zabbix is silent enough, then this can be closed for now and get reopened once it's needed on a better automated level.

@lemoer said something about a different approach regarding sending monitoring to peoplewho wher active in the last  hours using ansible; maybe we can talk about this next thursday.

However, thanks @moridius for implementing this!
