### ISSUE TITLE
Remove apinger webinterface

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#75]

**Comment by AiyionPrime** [comment]
https://github.com/freifunkh/ansible/blob/3c2f8a64f65ba67b20215bd65cca18eaa2bf3c27/roles/ffh.apinger/tasks/main.yml#L38
removing this might help?

I wished I had never looked into that role.

**Comment by AiyionPrime** [comment]
The author officially marked the project as abandoned yesterday -.-'
https://github.com/Jajcus/apinger/issues/4#issuecomment-778036966

**Comment by AiyionPrime** [comment]
@lemoer What do we use apinger for?

**Comment by lemoer** [comment]
There are currently two interfaces:
1. The [Grafana Panel](https://stats.ffh.zone/d/jdRuYDYWz/supernodes-splitted?viewPanel=288&orgId=1).
2. A [direct web-interface](http://sn10.s.ffh.zone:8765/cgi-bin/apinger) on the supernodes.

I would like to keep 1., but 2. can be removed.

**Comment by 1977er** [comment]
apinger no longer has an installation candidate on current Debians. We need an alternative.

**Comment by 1977er** [comment]
apinger is dead. Long live apinger!

What was the initial motivation behind this issue? Can we close it? @lemoer

**Comment by 1977er** [comment]
Could we - at least - close the firewall on port 8765? @lemoer

**Comment by 1977er** [comment]
Fixed with 61d4e0bf9a6cb26be7aa5b4850d0e7733e81d917.
