### ISSUE TITLE
fqdn role?

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#77]
@1977er, yesterday you talked about setting the fqdn of our hosts;
As the hostname is currently set manually on sn07, this will be gone as soon as I'll reset the server tomorrow afternoon.
You talked about ansible roles for this job; how ever you decide on this, keep in mind to change /etc/hosts as well, as it currently still contains the old hostname for 127.0.1.1 .

**Comment by 1977er** [comment]
Eventually I did not change the hostname, but used a self defined variable (fqdn) instead of relying on ansible_fqdn.

**Comment by AiyionPrime** [comment]
Alright.
