### ISSUE TITLE
Use etckeeper

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#79]
https://www.centrias.de/blog/ansible-prepost-hooks/

**Comment by lemoer** [comment]
Use "local_action" to get the running username.

**Comment by lemoer** [comment]
Implemented in the supernode playbook in b7b98b7d51c1a83096e912c1177b12cc97eb8c7c and 6dc89fcabf5c8034a42b62dadbbec07629de8b30.

Currently the git commits look like this:
```
[root@sn01]:~ # cd /etc
[root@sn01]:/etc # git log
commit ae36191a302c4d55b31357bfeaf04df98e0a9f7a
Author: root <root@sn01.s.ffh.zone>
Date:   Fri Jul 3 00:01:14 2020 +0200

    pre-commit changes before Ansible runs (lemoer@orange, tags: foobar, ffh.etckeeper)

```

Some explanation:
- The information `lemoer@orange` is obtained from your local machine.
- The information `tags` is obtained from the ansible variable `ansible_run_tags`.

Currently the state of */etc/* is committed two times during a single `ansible-playbook` invokation. One is *"pre-commit"* before ansible has started to roll and one is *"post-commit"* after the ansible roles have been applied.

As git only creates commits when something has actually changed, the *"pre-commit"* commit should almost never be created. Only when someone has bypassed ansible and has done manual changes in */etc/*, such a commit will be created the next time someone is rolling ansible.

Therefore I would suggest that we create a zabbix-trigger when the output of `git log --oneline | grep pre-commit` changes. I think this should create a warning which should be acked by one of us then.

What do you think @1977er ?

**Comment by 1977er** [comment]
I'd suggest `git log --oneline | sha256sum` to reduce the data collected by Zabbix. Why do you grep for pre-commit only? Isn't it useful to be notified for all changes?

**Comment by 1977er** [comment]
Okay, might be too much noise.

**Comment by 1977er** [comment]
Implemented in 0cda41598a802b747ecb4bd2661d05b74c1a8975.

**Comment by lemoer** [comment]
There is still something to do here.

1. Die Tatsache, dass unsere peers in /etc/fastd/peers liegen, erzeugt noise im etckeeper.
2.  Ich glaube, der Approach ist sowieso broken, fällt mir gerade auf. nicht nur im bezug auf die fastd peers, sondern auch allgemein. die notification schlägt ja eh nur alarm beim "pre-commit" vom ansible. wenn die änderung aber schon "vom daily commit aufgefressen" wurde, dann bekommen wir das gar nicht mit

To solve this:
1. Add a .gitignore in /etc/fastd
2. I would suggest something like this:
`
git log --oneline | grep -e '\(daily autocommit\|prior to apt run\|pre-commit\)'
`

**Comment by lemoer** [comment]
Maybe also nice:
```
[root@sn09]:/etc # git -C /etc log --pretty=format:"%ad %s" --date=short | grep 'post-commit' | cut -d ' ' -f 1,7-
2020-07-19 (okrueger@hub, tags: zabbix-agent)
2020-07-04 (okrueger@hub, tags: zabbix-agent)
2020-07-04 (okrueger@hub, tags: zabbix-agent)
2020-07-03 (okrueger@hub, tags: zabbix-agent)
2020-07-03 (okrueger@hub, tags: zabbix-agent)
2020-07-03 (okrueger@hub, tags: zabbix-agent)
```

This returns the last ansible runs on this host.

**Comment by CodeFetch** [comment]
@lemoer Sounds like a simple change. Why don't you implement it?

**Comment by lemoer** [comment]
Done in a6ece1db4550b917c0216528b22b99a623ddd248 .
