### ISSUE TITLE
Harvester Will not be Connected Anymore in Future

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#84]
@1977er You retired the mesh_fastd_remotes_backbone role.

https://github.com/freifunkh/ansible/blob/6d888841803bc0b2e954aa8ef21315a30950d2a1/roles/archive/ffh.mesh_fastd_remotes_backbone/templates/backbone.conf.j2#L1-L7

Did you had any idea in mind, how Harvester will be connected in the future? As of now, it's only connected to sn01 and sn08, as they were rolled prior to this change.

Another problem will be if harvester will be rolled out from scratch. See `/etc/fastd/mesh_fastd/backbone.conf` on Harvester. The supernode-Pubkeys are listed here in that way.

**Comment by 1977er** [comment]
Oops. I was convinced that there were gretaps which replaced the fastd connections.

**Comment by AiyionPrime** [comment]
Today is the day.

**Comment by AiyionPrime** [comment]
#99 for any more hotfixes.

I'm quite eager to hear why it was a good idea to leave this issue floating -.-'

**Comment by 1977er** [comment]
Fixed in 1a8b4d4268aeaa7d97eb2463541a27ee77277072 and 2297a9d8849dd318e948269d611471ec0e305fab.
