### ISSUE TITLE
Secondary Nameservers are not Resolvable Anymore

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#85]
```
[root@sn08]:~ # host ns1.ffh.zone
ns1.ffh.zone has address 37.120.176.252
ns1.ffh.zone has IPv6 address 2a03:4000:6:8277::1
[root@sn08]:~ # host ns3.ffh.zone
Host ns3.ffh.zone not found: 3(NXDOMAIN)
[root@sn08]:~ # host ns2.ffh.zone
Host ns2.ffh.zone not found: 3(NXDOMAIN)
[root@sn01]:~ # host ns1.ffh.zone 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

ns1.ffh.zone has address 37.120.176.252
ns1.ffh.zone has IPv6 address 2a03:4000:6:8277::1
[root@sn01]:~ # host ns2.ffh.zone 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

Host ns2.ffh.zone not found: 3(NXDOMAIN)
[root@sn01]:~ # host ns3.ffh.zone 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

Host ns3.ffh.zone not found: 3(NXDOMAIN)
[root@sn01]:~ # 
```

**Comment by lemoer** [comment]
@Manawyrm Could you maybe have a look on this issue?

**Comment by 1977er** [comment]
Have they ever been? I think we had entries for ns1.ffh.zone, but not for ns2 or ns3. @lemoer do you mix that up with ns1.fnorden.net et al?

**Comment by Manawyrm** [comment]
Yeah, secondary NS for .fnorden.net is being hosted by he.net, there's no secondary DNS for the ffh.zone, not sure why these days. Presumably because the same host was hosting some centralized infrastructure and it didn't make sense to have the DNS redundant but not the infrastructure itself? Not so sure.

**Comment by lemoer** [comment]
@1977er You are right. I mixed that up with `ns2.fnorden.net.` and `ns3.fnorden.net.`. From my side, this can be closed then.
