### ISSUE TITLE
sn07: weird interface errors

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#98]
Using `systemctl list-units --all --type service` on sn07 results in output like this:

```
  UNIT                                           LOAD      ACTIVE   SUB     DESCRIPTION                               
  add-gt-to-batX@0.service                       loaded    inactive dead    add-gt-to-batX@0.service                  
● add-gt-to-batX@10.service                      loaded    failed   failed  add-gt-to-batX@10.service                 
● add-gt-to-batX@11.service                      loaded    failed   failed  add-gt-to-batX@11.service                 
● add-gt-to-batX@12.service                      loaded    failed   failed  add-gt-to-batX@12.service                 
  add-gt-to-batX@13.service                      loaded    inactive dead    add-gt-to-batX@13.service                 
● add-gt-to-batX@14.service                      loaded    failed   failed  add-gt-to-batX@14.service                 
  add-gt-to-batX@15.service                      loaded    inactive dead    add-gt-to-batX@15.service                 
● add-gt-to-batX@16.service                      loaded    failed   failed  add-gt-to-batX@16.service                 
● add-gt-to-batX@17.service                      loaded    failed   failed  add-gt-to-batX@17.service                 
● add-gt-to-batX@18.service                      loaded    failed   failed  add-gt-to-batX@18.service                 
  add-gt-to-batX@19.service                      loaded    inactive dead    add-gt-to-batX@19.service                 
  add-gt-to-batX@20.service                      loaded    inactive dead    add-gt-to-batX@20.service                 
  add-gt-to-batX@21.service                      loaded    inactive dead    add-gt-to-batX@21.service                 
● add-gt-to-batX@22.service                      loaded    failed   failed  add-gt-to-batX@22.service                 
  add-gt-to-batX@23.service                      loaded    inactive dead    add-gt-to-batX@23.service                 
● add-gt-to-batX@99.service                      loaded    failed   failed  add-gt-to-batX@99.service                 
  add-vx-to-batX@10.service                      loaded    inactive dead    add-vx-to-batX@10.service                 
● add-vx-to-batX@11.service                      loaded    failed   failed  add-vx-to-batX@11.service                 
  add-vx-to-batX@12.service                      loaded    inactive dead    add-vx-to-batX@12.service                 
● add-vx-to-batX@13.service                      loaded    failed   failed  add-vx-to-batX@13.service                 
● add-vx-to-batX@14.service                      loaded    failed   failed  add-vx-to-batX@14.service                 
  add-vx-to-batX@15.service                      loaded    inactive dead    add-vx-to-batX@15.service                 
  add-vx-to-batX@16.service                      loaded    inactive dead    add-vx-to-batX@16.service                 
  add-vx-to-batX@17.service                      loaded    inactive dead    add-vx-to-batX@17.service                 
● add-vx-to-batX@18.service                      loaded    failed   failed  add-vx-to-batX@18.service                 
● add-vx-to-batX@19.service                      loaded    failed   failed  add-vx-to-batX@19.service                 
● add-vx-to-batX@20.service                      loaded    failed   failed  add-vx-to-batX@20.service                 
  add-vx-to-batX@21.service                      loaded    inactive dead    add-vx-to-batX@21.service                 
● add-vx-to-batX@22.service                      loaded    failed   failed  add-vx-to-batX@22.service                 
● add-vx-to-batX@23.service                      loaded    failed   failed  add-vx-to-batX@23.service                 
  add-vx-to-batX@99.service                      loaded    inactive dead    add-vx-to-batX@99.service                 
● addbrl2tptobatX@10.service                     loaded    failed   failed  addbrl2tptobatX@10.service                
  addbrl2tptobatX@11.service                     loaded    inactive dead    addbrl2tptobatX@11.service                
● addbrl2tptobatX@12.service                     loaded    failed   failed  addbrl2tptobatX@12.service                
● addbrl2tptobatX@13.service                     loaded    failed   failed  addbrl2tptobatX@13.service                
  addbrl2tptobatX@14.service                     loaded    inactive dead    addbrl2tptobatX@14.service                
  addbrl2tptobatX@15.service                     loaded    inactive dead    addbrl2tptobatX@15.service                
● addbrl2tptobatX@16.service                     loaded    failed   failed  addbrl2tptobatX@16.service                
● addbrl2tptobatX@17.service                     loaded    failed   failed  addbrl2tptobatX@17.service                
  addbrl2tptobatX@18.service                     loaded    inactive dead    addbrl2tptobatX@18.service                
● addbrl2tptobatX@19.service                     loaded    failed   failed  addbrl2tptobatX@19.service                
● addbrl2tptobatX@20.service                     loaded    failed   failed  addbrl2tptobatX@20.service                
● addbrl2tptobatX@21.service                     loaded    failed   failed  addbrl2tptobatX@21.service                
  addbrl2tptobatX@22.service                     loaded    inactive dead    addbrl2tptobatX@22.service                
● addbrl2tptobatX@23.service                     loaded    failed   failed  addbrl2tptobatX@23.service                
● addbrl2tptobatX@99.service                     loaded    failed   failed  addbrl2tptobatX@99.service              
```  

Neither is this the case on other supernodes for `add-gt-to-batX@.service`, nor did this happen yesterday.
Something mangles our network related services during boot.

This could either be changes of me in #95, changes of @CodeFetch in #94 or even changes on master.

I'll role out every ansible task in master on sn08 this evening, and will **wipe** sn07 tomorrow at 11:00 o'clock.
@CodeFetch, @lemoer, @1977er: Please backup any unsafed changes of yours beforehand!

I'll then continue to reapply #95 to determine if this reintroduces the error.

At last I'll reapply #94 in order to get back to the current state again.

If any of you finds the issue beforehand, please answer below to safe me from a lot of trouble...

**Comment by AiyionPrime** [comment]
Mit master scheint das wenig zu tun zu haben; auf sn08 habe ich den vollständig ausgerollt und treffe keine Besonderheiten.
Der Output vor und nach dem update liegt hier aber is unauffällig:

[before master](https://bpa.st/IZHQ) [after master](https://bpa.st/GTXA)

Therefore the next point on my list is reinstalling sn07 with master at 11am.

**Comment by AiyionPrime** [comment]
Und wie sie unschwer am Denglisch erkennen können, gehe ich jetzt besser schlafen.

**Comment by AiyionPrime** [comment]
I'm done resetting sn07.
Applying only master results in a clean start of the 'add-gt-to-batX@XX.service's.
Putting #95 as well results in 7/25 add services failing.
I'd like to note this is far from 50%, quite possible, that more interfaces/services worsen the effect.

**Comment by AiyionPrime** [comment]
Lasst uns kurz über diese Zeile in den wackeligen Services reden: (die 10 exemplarisch)
`ExecStart=/usr/sbin/batctl meshif bat10 if add vlan-gt-210`

Während der Befehl dafür gedacht ist, `vlan-gt-210`zu `bat10` hinzuzufügen, sollte er, da `-M` nicht benutzt wurde, das interface `bat10` zur Not auch erstellen, wenn es noch nicht existiert.

Also welchen Grund gibt es noch, warum als Fehler:

> batctl[1044]: Error - failed to create batman-adv interface: File exists

zurückkommen kann?

**Comment by lemoer** [comment]
Falls noch nicht gelöst:

> Also welchen Grund gibt es noch, warum als Fehler:
>
> batctl[1044]: Error - failed to create batman-adv interface: File exists
>
> zurückkommen kann?
>
Evtl. weil das Iface schon zum bat10 hinzugefügt wurde?


Am Do., 7. Jan. 2021 um 18:11 Uhr schrieb J. Burfeind <
notifications@github.com>:

**Comment by AiyionPrime** [comment]
Ist noch nicht gelöst.

> Evtl. weil das Iface schon zum bat10 hinzugefügt wurde?

`batctl meshif bat10 if add vx-10` kann man mehrmal hintereinander ausführen, ohne das sich an der Ausgabe von `batctl meshif bat10 if` etwas ändern würde, odr man einen Fehler erhielte.

**Comment by lemoer** [comment]
Hm. Ok. Ich bin gegen Nachmittag im Mumble. Dann können wir gern schauen.

Am Fr., 8. Jan. 2021 um 12:15 Uhr schrieb J. Burfeind <
notifications@github.com>:

**Comment by AiyionPrime** [comment]
Bin nich vor 15:00 da; aber gerne

**Comment by AiyionPrime** [comment]
habe in #batman gerade eine Rückmeldung von ecsv erhalten; werde die später mal testen.

**Comment by AiyionPrime** [comment]
So; my current suspicion is this:
while `batctl meshif bat10 add vx-11` should add bat10 if it did not exist according to its man page; it might just not be thread safe.
Currently I leave bat creation to the fastd roles tasks; and simply wait for bat11 to appear.

This works fine; while it's neither a permanent solution; nor is it implemented in #94 .

**Comment by 1977er** [comment]
Suggesting "Decide how and where to create bat interfaces" as new title, since this is supernode-agnostic.

**Comment by AiyionPrime** [comment]
This was about finding the reason for 'weird inteface errors on sn07'.
The reason is found, the only thing missing is @CodeFetch closing this as soon as he implemented a fix he is satisfied with on his PR. Or has already done this.

**Comment by 1977er** [comment]
The aftermath is handled in #111 (and probably somehere else). Can we close this?

**Comment by AiyionPrime** [comment]
No. Codefetch silence does almost never mean, "I found time to implement this, just forgot to close this.".
I still think he should close this, if he took care of it in his PR.
